### gradle performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

### build
javaVersion=25
kotlinVersion=2.3.0
springBootVersion=4.0.6
springDependencyManagementVersion=1.1.7
springCloudVersion=2025.1.1
springdocVersion=3.0.3

### test
kotestVersion=6.1.11
