spring:
  application:
    name: common-config
  threads:
    virtual:
      enabled: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /openapi
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    display-request-duration: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring.config.activate.on-profile: local

GIT_CONFIG_REPO_URI: http://localhost:3100/common-config/config-repo.git
GIT_CONFIG_REPO_DEFAULT_LABEL: main

VAULT_HOST: localhost
VAULT_PORT: 8200
VAULT_SCHEME: http
VAULT_TOKEN: example

---
spring.config.activate.on-profile: onprem
