spring:
  cloud:
    config:
      server:
        prefix: /config
        vault:
          backend: kv
          kv-version: 2
          profile-separator: /
          authentication: TOKEN

---
spring.config.activate.on-profile: local

spring:
  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          token: example

---
spring.config.activate.on-profile: onprem

spring:
  cloud:
    config:
      server:
        vault:
          host: ${OPENBAO_HOST}
          port: ${OPENBAO_PORT}
          scheme: ${OPENBAO_SCHEME}
          token: ${OPENBAO_TOKEN}
